/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cs.assignment;

import java.util.Scanner;
import org.apache.log4j.Logger;
import com.cs.assignment.service.FileProcessingService;
import com.cs.assignment.service.impl.FileProcessingServiceImpl;

public class LogFileAnalyser {

	private static Logger logger = Logger.getLogger(LogFileAnalyser.class);

	public static void main(String[] args) {
		Scanner reader = new Scanner(System.in);
		System.out.println("Enter file name for analysis ");
		String fileName = reader.next();
		System.out.println("Data to be stored in file? Enter true or flase ");
		boolean dbGrantIssue = Boolean.parseBoolean(reader.next());
		reader.close();

		logger.info("The log file processing stated for event analysis, file name : "
				+ fileName);
		FileProcessingService fileProcessingService = new FileProcessingServiceImpl();
		long startTime = System.currentTimeMillis();
		// job
		String response = fileProcessingService.processFile(fileName,
				dbGrantIssue);

		long endTime = System.currentTimeMillis();
		logger.info("Log file analyser job completed in  "
				+ (endTime - startTime) + " ms");
		logger.info("File processing response: " + response);
	}
}
